server:
  port: 0

spring:
  datasource:
    url: ${MAIN_DB_URL:jdbc:postgresql://localhost:6541/ewm-main}
    username: ${MAIN_DB_USER:main}
    password: ${MAIN_DB_PASSWORD:main}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false