services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
      - POSTGRES_DB=ewm-stats
    volumes:
      - stats-db-data:/var/lib/postgresql/data/
      - ./stats/stats-server/src/main/resources/schema-stat.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stat -d ewm-stats"]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  stats-server:
    build: ./stats/stats-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    restart: on-failure

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - POSTGRES_DB=ewm-main
    volumes:
      - ewm-db-data:/var/lib/postgresql/data/
      - ./core/event-service/src/main/resources/schema-main.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U main -d ewm-main" ]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: on-failure

  ewm-service:
    build: ./core/event-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    restart: on-failure

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init-topics
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # Ожидаем готовности брокера
      kafka-topics --bootstrap-server kafka:29092 --list
      echo 'Создаем топики Kafka...'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic stats.user-actions.v1 --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic stats.events-similarity.v1 --replication-factor 1 --partitions 1
      echo 'Топики успешно созданы:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

volumes:
  stats-db-data:
  ewm-db-data: