main-server.url=http://localhost:8080
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://stats-db:6542/ewm-stats
spring.datasource.username=stat
spring.datasource.password=stat

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.application.name=stats-server
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-stat.sql