server:
  port: 8080

spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: request-service-user-requests-base
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests
        - id: request-service-user-requests-sub
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**

        - id: request-service-event-requests-base
          uri: lb://request-service
          predicates:
            - Path=/users/*/events/*/requests
        - id: request-service-event-requests-sub
          uri: lb://request-service
          predicates:
            - Path=/users/*/events/*/requests/**

        - id: user-service-users-base
          uri: lb://user-service
          predicates:
            - Path=/admin/users
        - id: user-service-users-sub
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: comment-service-user-comments
          uri: lb://comment-service
          predicates:
            - Path=/users/*/events/*/comments/**
        - id: comment-service-public-comments
          uri: lb://comment-service
          predicates:
            - Path=/events/*/comments/**
        - id: comment-service-admin-comments-base
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments
        - id: comment-service-admin-comments-sub
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        - id: event-service-route
          uri: lb://event-service
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: health, gateway
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}